/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * Simple Java SQL database wrapper.<br>
 * <p>
 * Supports easier connection management; translation of a ResultSet into a
 * Collection; insert, update and delete Java objects into an SQL database.
 * <p>
 * <h5>Dependencies.</h5><br>
 * Requires java 1.7 and higher.<br>
 * Usage of {@code SQLRecoverableException} and {@code SQLTransientException}
 * requires 1.6.<br>
 * Usage of {@code "SQLRecoverableException | SQLTransientException"} requires
 * 1.7.<br>
 * Usage of the Diamond operator ({@code "<>"}) requires 1.7.
 * 
 * <p>
 * Can be used with Tomcat 8.0 and higher (Tomcat 8 requires java 1.7).
 * <p>
 * <h5>Limitations.</h5><br>
 * Limitation: does not support multiple updates for 1 java class, where each
 * update has a different set of attributes. Example: RaboTransaction:
 * update-scenario, approve-scenario and set-match/classification-scenario.
 * <p>
 * Limitation: does not support to map 1 java class on more than 1 database
 * table. Example: RaboRule maps to rabo_match and to rabo_classification.
 * <h5>Assumptions.</h5><br>
 * Assumption: PK consists of exactly 1 database column.
 * <p>
 * Assumption: PK-value is generated by the database on INSERT.
 * <p>
 * 
 * @version 1.0
 */
package org.mikel.dbwrapper;

