/* Generated By:JavaCC: Do not edit this line. SegParserConstants.java */
package org.subwayworld.metrogen.segparser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface SegParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int K_SEGMENT = 6;
  /** RegularExpression Id. */
  int K_FORWARD = 7;
  /** RegularExpression Id. */
  int K_FORWARDEND = 8;
  /** RegularExpression Id. */
  int K_BACKWARD = 9;
  /** RegularExpression Id. */
  int K_BACKWARDEND = 10;
  /** RegularExpression Id. */
  int K_STATIONS = 11;
  /** RegularExpression Id. */
  int K_STATIONSEND = 12;
  /** RegularExpression Id. */
  int K_SEGMENTEND = 13;
  /** RegularExpression Id. */
  int K_CITY = 14;
  /** RegularExpression Id. */
  int K_CITYEND = 15;
  /** RegularExpression Id. */
  int K_CITYCODE = 16;
  /** RegularExpression Id. */
  int K_CITYCODE_END = 17;
  /** RegularExpression Id. */
  int K_CITYNAME = 18;
  /** RegularExpression Id. */
  int K_CITYNAME_END = 19;
  /** RegularExpression Id. */
  int K_LINETYPE = 20;
  /** RegularExpression Id. */
  int K_LINETYPE_END = 21;
  /** RegularExpression Id. */
  int K_MULTI_NAMED_NODE = 22;
  /** RegularExpression Id. */
  int K_MULTI_NAMED_NODE_END = 23;
  /** RegularExpression Id. */
  int K_SERVICE_TYPE = 24;
  /** RegularExpression Id. */
  int K_SERVICE_TYPE_END = 25;
  /** RegularExpression Id. */
  int K_METRO_TRANSFORM = 26;
  /** RegularExpression Id. */
  int K_METRO_TRANSFORM_END = 27;
  /** RegularExpression Id. */
  int K_TRANSFORM_POINT = 28;
  /** RegularExpression Id. */
  int K_TRANSFORM_POINT_END = 29;
  /** RegularExpression Id. */
  int K_BEFORE = 30;
  /** RegularExpression Id. */
  int K_BEFORE_END = 31;
  /** RegularExpression Id. */
  int K_AFTER = 32;
  /** RegularExpression Id. */
  int K_AFTER_END = 33;
  /** RegularExpression Id. */
  int K_LINE_REMARK = 34;
  /** RegularExpression Id. */
  int K_LINE_REMARK_END = 35;
  /** RegularExpression Id. */
  int K_LINE_EDIT = 36;
  /** RegularExpression Id. */
  int K_LINE_EDIT_END = 37;
  /** RegularExpression Id. */
  int K_LINE = 38;
  /** RegularExpression Id. */
  int K_LINE_END = 39;
  /** RegularExpression Id. */
  int K_LINE_NAME = 40;
  /** RegularExpression Id. */
  int K_LINE_NAME_END = 41;
  /** RegularExpression Id. */
  int K_NAME = 42;
  /** RegularExpression Id. */
  int K_NAME_END = 43;
  /** RegularExpression Id. */
  int K_OVERRIDE_SEGMENT = 44;
  /** RegularExpression Id. */
  int K_OVERRIDE_SEGMENT_END = 45;
  /** RegularExpression Id. */
  int K_OVERRIDE_SECTION = 46;
  /** RegularExpression Id. */
  int K_OVERRIDE_STATIONS = 47;
  /** RegularExpression Id. */
  int K_OVERRIDE_SECTION_END = 48;
  /** RegularExpression Id. */
  int Id = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
      "<SINGLE_LINE_COMMENT>", "\"SEGMENT\"", "\"FORWARD\"", "\"FORWARDEND\"",
      "\"BACKWARD\"", "\"BACKWARDEND\"", "\"STATIONS\"", "\"STATIONSEND\"",
      "\"SEGMENTEND\"", "\"CITY\"", "\"CITYEND\"", "\"CITYCODE\"",
      "\"CITYCODE_END\"", "\"CITYNAME\"", "\"CITYNAME_END\"", "\"LINETYPE\"",
      "\"LINETYPE_END\"", "\"MULTI_NAMED_NODE\"", "\"MULTI_NAMED_NODE_END\"",
      "\"SERVICETYPE\"", "\"SERVICETYPEEND\"", "\"METRO_TRANSFORM\"",
      "\"METRO_TRANSFORM_END\"", "\"TRANSFORM_POINT\"",
      "\"TRANSFORM_POINT_END\"", "\"BEFORE\"", "\"BEFORE_END\"", "\"AFTER\"",
      "\"AFTER_END\"", "\"LINE_REMARK\"", "\"LINE_REMARK_END\"",
      "\"LINE_EDIT\"", "\"LINE_EDIT_END\"", "\"LINE\"", "\"LINE_END\"",
      "\"LINE_NAME\"", "\"LINE_NAME_END\"", "\"NAME\"", "\"NAME_END\"",
      "\"OVERRIDE_SEGMENT\"", "\"OVERRIDE_SEGMENT_END\"",
      "\"OVERRIDE_SECTION\"", "\"OVERRIDE_STATIONS\"",
      "\"OVERRIDE_SECTION_END\"", "<Id>", };

}
